#!/usr/bin/python

import os
import argparse
import tempfile
import subprocess
import wikipedia
import requests
from bs4 import BeautifulSoup
from pathlib import Path

parser = argparse.ArgumentParser(description='Add episode titles to the episode files of a show.')
parser.add_argument('-e', '--edit', action='store_true', help='edit episode titles before renaming episode files')
parser.add_argument('-n', '--nochange', action='store_true', help='print outcome but make no changes to episode files')
parser.add_argument('-d', '--dir', help='directory containing the episode files to be renamed')
parser.add_argument('-f', '--file', help='file containing existing episode titles')
parser.add_argument('show', help='name of the show to search for episode titles of')

args = parser.parse_args()
titles = []
files = []

def get_titles():
  editor = os.environ.get('EDITOR', 'vi')
  if args.file:
    titleFile = args.file
    
    if args.edit == True:
      subprocess.call([editor, titleFile])
    
    with open(titleFile, "r") as file:
      for line in file:
        titles.append(line.rstrip())
  else:
    showName = args.show
    searchQuery = "List of " + showName + " episodes"
    searchResult = wikipedia.search(searchQuery, results=1)
    
    if searchResult:
      showPage = wikipedia.page(searchResult[0], pageid = None, auto_suggest = False)
      response = requests.get(url=showPage.url)
      soup = BeautifulSoup(response.content, 'html.parser')
      items = soup.find(id="mw-content-text").find_all(class_="summary")
      tempFile = tempfile.NamedTemporaryFile()
      
      with open(tempFile.name, "w") as file:
        for item in items:
          print(item.get_text(), file=file)
      
      subprocess.run(['sed', '-i', '/^List of.*episodes$/d;/^Release$/d;s/^"//g;s/".*$//g;s/:/-/g;s/\?/_/g', tempFile.name])
      
      if args.edit == True:
        subprocess.call([editor, tempFile.name])
      
      with open(tempFile.name, "r") as file:
        for line in file:
          titles.append(line.rstrip())

def get_files():
  if args.dir:
    workingDir = args.dir
  else:
    workingDir = Path.cwd()
  path = Path(workingDir)
  for path in path.rglob('*'):
    file = Path(path)
    if file.is_file():
      files.append(file)

def rename_files():
  if len(files) == len(titles):
    for file, title in zip(files, titles):
      f = Path(file)
      name, ext = f.stem, f.suffix
      newName = name + ' - ' + title + ext
      if args.nochange == True:
        print(newName)
      else:
        f.rename(newName)
  else:
    print('error: number of files and titles do not match')

get_titles()
get_files()
rename_files()